version: "3.7"
services:
  db:
    container_name: pg_container
    image: postgres:12
    networks: ['webnet']
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST: psqlhost
      POSTGRES_USER: psqluser
      POSTGRES_PASSWORD: psqlpassword
      POSTGRES_DB: psqldb

    ports:
        - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:4.29
    networks: ['webnet']
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  web:
    container_name: testApp
    image: bs/outside
    ports:
      - 8080:3000
    networks: ['webnet']
    environment:
      - POSTGRES_HOST=psqlhost
      - POSTGRES_USER=psqluser
      - POSTGRES_PASSWORD=psqlpassword
      - POSTGRES_DB=psqldb
networks:
  webnet: