version: "3.7"
services:
  db:
    container_name: pg_container
    image: postgres:12
    networks: ['webnet']
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:4.29
    networks: ['webnet']
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  web:
    container_name: testApp_container
    image: ${IMAGE_NAME}
    ports:
      - 8080:3000
    networks: ['webnet']
    environment:
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - PG_DB=${PG_DB}
      - PG_PASSWORD=${PG_PASSWORD}
networks: ['webnet']